### ISSUE TITLE
Issues with Kernel 5.8

### ISSUE THREAD

**Issue by gissf1** [trya/mach64-drm#3]
This doesn't seem to build against my Kernel 5.8.14.  I'm using Arch Linux 32 through the AUR package, but the AUR build script has some other pending issues at the moment, so I'd suggest building against a stock 5.8.x kernel.

It seems like the `drm/drm_pci.h` header included from `mach64_dma.c` has been moved or renamed in the kernel headers.  I think it was renamed to `drm/drm_legacy.h`, but even after swapping that header name, I wasn't able to build due to other build errors.

Let me know if you need anything more from me, and thanks for bringing this component back to life!

**Comment by trya** [comment]
Should build with linux 5.8 onwards now, but you need to build your kernel with CONFIG_DRM_LEGACY (stock Arch kernel won't do).
